apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: kubeflow-pipeline-for-eddl-demo-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.11, pipelines.kubeflow.org/pipeline_compilation_time: '2022-04-05T16:32:41.208949',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "Kubeflow pipeline demo
      with simple EDDL model training", "name": "Kubeflow pipeline for EDDL demo"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.11}
spec:
  entrypoint: kubeflow-pipeline-for-eddl-demo
  templates:
  - name: kubeflow-pipeline-for-eddl-demo
    dag:
      tasks:
      - name: test-model
        template: test-model
        dependencies: [train-model]
        arguments:
          artifacts:
          - {name: train-model-model, from: '{{tasks.train-model.outputs.artifacts.train-model-model}}'}
          - {name: train-model-x_test, from: '{{tasks.train-model.outputs.artifacts.train-model-x_test}}'}
          - {name: train-model-y_test, from: '{{tasks.train-model.outputs.artifacts.train-model-y_test}}'}
      - {name: train-model, template: train-model}
  - name: test-model
    container:
      args: [/tmp/inputs/input-0/data, /tmp/inputs/input-1/data, /tmp/inputs/input-2/data]
      image: nannakaroliina/eddlpredict:latest
    inputs:
      artifacts:
      - {name: train-model-model, path: /tmp/inputs/input-0/data}
      - {name: train-model-x_test, path: /tmp/inputs/input-1/data}
      - {name: train-model-y_test, path: /tmp/inputs/input-2/data}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.11
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  - name: train-model
    container: {image: 'nannakaroliina/eddltrain:latest'}
    outputs:
      artifacts:
      - {name: train-model-architecture, path: app/model.pdf}
      - {name: train-model-model, path: /app/simple_CNN.bin}
      - {name: train-model-x_test, path: app/cifar_tsX.bin}
      - {name: train-model-x_train, path: app/cifar_trX.bin}
      - {name: train-model-y_test, path: app/cifar_tsY.bin}
      - {name: train-model-y_train, path: app/cifar_trY.bin}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.11
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
