apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: kubeflow-feast-demo-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.10, pipelines.kubeflow.org/pipeline_compilation_time: '2022-05-30T10:27:52.643850',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "Kubeflow pipeline demo
      with Feast", "name": "Kubeflow Feast demo"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.10}
spec:
  entrypoint: kubeflow-feast-demo
  templates:
  - name: kubeflow-feast-demo
    dag:
      tasks:
      - name: test-model
        template: test-model
        dependencies: [train-model]
        arguments:
          artifacts:
          - {name: train-model-featurestore, from: '{{tasks.train-model.outputs.artifacts.train-model-featurestore}}'}
          - {name: train-model-model, from: '{{tasks.train-model.outputs.artifacts.train-model-model}}'}
      - {name: train-model, template: train-model}
  - name: test-model
    container:
      args: [--featurestore, /tmp/inputs/input-0/data, --model, /tmp/inputs/input-1/data]
      image: nannakaroliina/feastpredict:latest
    inputs:
      artifacts:
      - {name: train-model-featurestore, path: /tmp/inputs/input-0/data}
      - {name: train-model-model, path: /tmp/inputs/input-1/data}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.10
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  - name: train-model
    container: {image: 'nannakaroliina/feasttrain:latest'}
    outputs:
      artifacts:
      - {name: train-model-featurestore, path: /app/feast_dir.zip}
      - {name: train-model-model, path: /app/model.joblib}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.10
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
