name: Docker
on:
  push:
    branches: [ eddl-cpp ]
  pull_request:
    branches: [ eddl-cpp ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
      - name: Build EDDL Train
        run: docker build ./train -t tuminguyen/train
      - name: Push EDDL Train
        run: docker push tuminguyen/train
      - name: Build EDDL Predict
        run: docker build ./predict -t tuminguyen/predict
      - name: Push EDDL Predict
        run: docker push tuminguyen/predict
