name: Docker
on:
  push:
    branches: [ pyeddl ]
  pull_request:
    branches: [ pyeddl ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
      - name: Build PyEDDL Train
        run: docker build ./train -t nannakaroliina/pyeddltrain
      - name: Push PyEDDL Train
        run: docker push nannakaroliina/pyeddltrain
      - name: Build PyEDDL Predict
        run: docker build ./predict -t nannakaroliina/pyeddlpredict
      - name: Push PyEDDL Predict
        run: docker push nannakaroliina/pyeddlpredict
