name: Docker
on:
  push:
    branches: [ kubeflow-feast ]
  pull_request:
    branches: [ kubeflow-feast ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
      - name: Build the Train image
        run: docker build ./train_model --tag nannakaroliina/feasttrain
      - name: Push the Train image
        run: docker push nannakaroliina/feasttrain
      - name: Build the Predict image
        run: docker build ./predict --tag nannakaroliina/feastpredict
      - name: Push the Predict image
        run: docker push nannakaroliina/feastpredict