name: Docker
on:
  commit:
    branches: [ mlflow-integration ]
  push:
    branches: [ mlflow-integration ]
  pull_request:
    branches: [ mlflow-integration ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
      - name: Build the Preprocess image
        run: docker build ./preprocess_data --tag nannakaroliina/kubeflow_pipeline_mlflow_preprocessing
      - name: Push the Preprocess image
        run: docker push nannakaroliina/kubeflow_pipeline_mlflow_preprocessing
      - name: Build the Train image
        run: docker build ./train_model --tag nannakaroliina/kubeflow_pipeline_mlflow_train
      - name: Push the Train image
        run: docker push nannakaroliina/kubeflow_pipeline_mlflow_train
      - name: Build the Predict image
        run: docker build ./predict --tag nannakaroliina/kubeflow_pipeline_mlflow_predict
      - name: Push the Predict image
        run: docker push nannakaroliina/kubeflow_pipeline_mlflow_predict